=== jagaidec/EBUT/Aufgabe2/Aufgabe2.1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY % preis "(Brutto | Netto)">

<!ELEMENT Produktkatalog (Header, Artikel+)>
	<!ELEMENT Header (Generierungsdatum, Name, Beschreibung?)>
		<!ELEMENT Generierungsdatum (#PCDATA)>
		<!ELEMENT Name (#PCDATA)><!--maximal Länge 50-->
		<!ELEMENT Beschreibung (#PCDATA)><!--maximal Länge 100-->
		
	<!ELEMENT Artikel (Kurzbeschreibung, Hersteller?, zusatz_ArtikelNr?, Langbeschreibung?, Preis, Artikel?)>
		<!ELEMENT Kurzbeschreibung (#PCDATA)><!--maximal Länge 80-->
		<!ELEMENT Hersteller (#PCDATA)><!--maximal Länge 50-->
		<!ELEMENT zusatz_ArtikelNr (#PCDATA)><!--maximal Länge 50-->
		<!ELEMENT Langbeschreibung (#PCDATA | Wichtig)*><!--maximal Länge 50--><!--<!Element Wichtig (#PCDATA)>-->
		<!ELEMENT Preis %preis;>
			<!ELEMENT Brutto (DerPreis, Kürzel, LandesKürzel, Steuersatz)>
			<!ELEMENT Netto (DerPreis, Kürzel, LandesKürzel, Steuersatz)>
				<!ELEMENT DerPreis (#PCDATA)>
				<!ELEMENT Kürzel (#PCDATA)>
				<!ATTLIST Kürzel Währung (EUR | USD | CHF | GBP) "EUR">
				<!ELEMENT LandesKürzel (#PCDATA)><!--maximal Länge 3-->
				<!ELEMENT Steuersatz (#PCDATA)>			
	<!ATTLIST Artikel ArtikelNr ID #REQUIRED>

=== jagaidec/EBUT/Aufgabenblatt1/Aufgabe2/xmlInstanzDok.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Produktkatalog SYSTEM "Aufgabe2.1.dtd">
<Produktkatalog>
	<Header>
		<Generierungsdatum>21.10.2014</Generierungsdatum>
		<Name>Katalog</Name>
	</Header>
	<Artikel ArtikelNr="ID1">
		<Kurzbeschreibung>Artikel1</Kurzbeschreibung>
		<Hersteller>Hersteller1</Hersteller>
		<zusatz_ArtikelNr>11111</zusatz_ArtikelNr>
		<Langbeschreibung>das ist der erste Arikel</Langbeschreibung>
		<Preis>
			<Netto>
				<DerPreis>10000</DerPreis>
				<Kürzel Währung="CHF"/>
				<LandesKürzel>"CH"</LandesKürzel>
				<Steuersatz>"12"</Steuersatz>
			</Netto>
		</Preis>
	</Artikel>
	<Artikel ArtikelNr="ID2">
		<Kurzbeschreibung>Artikel2</Kurzbeschreibung>
		<Hersteller>Hersteller2</Hersteller>
		<zusatz_ArtikelNr>2222</zusatz_ArtikelNr>
		<Langbeschreibung>das ist der zweite Arikel</Langbeschreibung>
		<Preis>
			<Brutto>
				<DerPreis>20000</DerPreis>
				<Kürzel Währung="EUR"/>
				<LandesKürzel>"D"</LandesKürzel>
				<Steuersatz>"19"</Steuersatz>
			</Brutto>
		</Preis>
	</Artikel>
	<Artikel ArtikelNr="ID3">
		<Kurzbeschreibung>Artikel3</Kurzbeschreibung>
		<Hersteller>Hersteller3</Hersteller>
		<zusatz_ArtikelNr>3333</zusatz_ArtikelNr>
		<Langbeschreibung>das ist der dritte Arikel</Langbeschreibung>
		<Preis>
			<Brutto>
				<DerPreis>30000</DerPreis>
				<Kürzel Währung="GBP"/>
				<LandesKürzel>"GB"</LandesKürzel>
				<Steuersatz>"0"</Steuersatz>
			</Brutto>
		</Preis>
	</Artikel>
</Produktkatalog>

=== jagaidec/EBUT/Aufgabe2/xmlInstanzDok.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--XML-Beispieldatei von XMLSpy generiert v2015 sp1 (http://www.altova.com)-->
<!DOCTYPE Produktkatalog SYSTEM "Aufgabe2.1.dtd">
<Produktkatalog>
	<Header>
		<Generierungsdatum>text</Generierungsdatum>
		<Name>text</Name>
	</Header>
	<Artikel ArtikelNr="ID1">
		<Kurzbeschreibung>text</Kurzbeschreibung>
		<Preis>
			<Brutto>
				<K端rzel>text</K端rzel>
				<LandesK端rzel>text</LandesK端rzel>
				<Steuersatz>text</Steuersatz>
			</Brutto>
		</Preis>
	</Artikel>
</Produktkatalog>
